#version: '3'
#
#services:
#  order-automation:
#    image:  'docker-spring-boot-postgres:latest'
#    build:
#      context: .
#    container_name: order-automation
#    ports:
#      - "1313:1313"
#    depends_on:
#      - pgdb
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgdb:5432/order_automation
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=111
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#
#  pgdb:
#    image: 'postgres:13.10-alpine'
#    restart: always
#    container_name: pgdb
#    ports:
#      - "5432:5432"
#    expose:
#      - 5432
#    environment:
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=111
#      - POSTGRES_HOST_AUTH_METHOD=trust
#      - POSTGRES_DB=order_automation
