services:
  - type: web
    name: my-spring-boot-app
    env: docker
    buildCommand: docker-compose build
    startCommand: docker-compose up -d
    healthCheckPath: /actuator/health
    numInstances: 1
    port: 8080