CREATE TABLE IF NOT EXISTS category
(
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    parent_category_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL
);