CREATE TABLE IF NOT EXISTS categories
(
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    parent_category_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL
);

ALTER TABLE categories
    ALTER COLUMN description SET DEFAULT NULL,
    ALTER COLUMN name SET DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS image JSON DEFAULT NULL;
